### ISSUE TITLE
Console settings doesn't show anything after deployment

### ISSUE THREAD

**Issue by akachroo762** [cloudstoragesec/terraform-aws-cloud-storage-security#14]
After the deployment of CSS console from the terraform module, I can't see anything in the Console settings section and this is the error I get:

![image](https://github.com/cloudstoragesec/terraform-aws-cloud-storage-security/assets/61110412/dea1db93-140d-4d82-b5b9-c85d90bf44a6)

Below are some logs from ECS:

- 2024-04-22 00:58:25.6813|WARN|Microsoft.AspNetCore.Components.Web.ErrorBoundary|Unhandled exception rendering component: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')|System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
- at System.Collections.Generic.List`1.get_Item(Int32 index)
- at CloudStorageScanConsole.Models.ConsoleConfigModel.GetConsoleCidr() in /CloudStorageScan/CloudStorageScanConsole/CloudStorageScanConsole/Models/ConsoleConfigModel.cs:line 453
- at CloudStorageScanConsole.Pages.Configuration.ConsoleSettings.ConsoleSettings.OnInitializedAsync() in /CloudStorageScan/CloudStorageScanConsole/CloudStorageScanConsole/Pages/Configuration/ConsoleSettings/ConsoleSettings.razor.cs:line 127
- at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
- at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
- 2024-04-22 00:58:24.6076|WARN|Microsoft.AspNetCore.Components.Web.ErrorBoundary|Unhandled exception rendering component: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')|System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
- at System.Collections.Generic.List`1.get_Item(Int32 index)
- at CloudStorageScanConsole.Models.ConsoleConfigModel.GetConsoleCidr() in /CloudStorageScan/CloudStorageScanConsole/CloudStorageScanConsole/Models/ConsoleConfigModel.cs:line 453
- at CloudStorageScanConsole.Pages.Configuration.ConsoleSettings.ConsoleSettings.OnInitializedAsync() in /CloudStorageScan/CloudStorageScanConsole/CloudStorageScanConsole/Pages/Configuration/ConsoleSettings/ConsoleSettings.razor.cs:line 127
- at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
- at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

@yeapiekiyay

**Comment by akachroo762** [comment]
FYI @sh-dan @rlisnoff-css

**Comment by sh-dan** [comment]
Resolved in v1.0.2+css7.08.000 release. Thanks!
